### ISSUE TITLE
Dialog not respecting open value

### ISSUE THREAD

**Issue by juliomuhlbauer** [chakra-ui/ark#1758] opened 2023-11-22 16:51 UTC
### Description

When setting a boolean to open, it acts like a defaultOpen.

https://github.com/chakra-ui/ark/assets/53458125/51d42de3-b6c0-4519-bd80-cf9f6179fe3b

### Link to Reproduction (or Detailed Explanation)

.

### Steps to Reproduce

Set a true or false on open in the Dialog component, and try to open and close.
It should not be able to overpass the open value as it is controlled.

### Ark UI Version

1.1.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by Omikorin** [comment] 2023-11-22 17:48
Hi, thank you for the notice.

We know about that and this issue is a duplicate of chakra-ui/zag#1027

**Closed** 2023-11-22 17:54 UTC
Labels: component: dialog
