### ISSUE TITLE
combobox keyboard navigation bug in filtering example

### ISSUE THREAD

**Issue by arekmaz** [chakra-ui/ark#2667] opened 2024-07-15 16:57 UTC
### Description

the issue is reproducible on park-ui website, but I get it too using ark-ui 3.5.0

currently on my website the old version is working properly https://arek-ui.arexoft.com/?q=Combobox

when I enter the example https://park-ui.com/react/docs/components/combobox,
click on combobox in demo,
using keyboard select "React",
then using keyboard delete the value to be empty, and using down arrow select "Vue" from the list

after clicking "Enter", "React" value reappears even tough I have just selected "Vue"

### Link to Reproduction (or Detailed Explanation)

https://park-ui.com/react/docs/components/combobox

### Steps to Reproduce

1. go to https://park-ui.com/react/docs/components/combobox
2. click on combobox in demo
3. using keyboard select "React",
4. then using keyboard delete the value to be empty, and using down arrow select "Vue" from the list

5. after clicking "Enter", "React" value reappears even tough  "Vue" was just selected

### Ark UI Version

3.5.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

### Additional Information

I have the same problem with my components after trying to upgrade to ark-ui 3.5.0

**Comment by segunadebayo** [comment] 2024-07-23 12:39
I can't reproduce this in Zag.js or Ark UI docs. So it's probably related to how this is set up in Park UI.

Perhaps it's already fixed but not released cc @cschroeter

**Comment by arekmaz** [comment] 2024-07-23 15:15
Here's a [repro sandbox](https://codesandbox.io/p/sandbox/empty-worker-2nn4f9?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyyjnsn700063b6jfmzh9inb%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyyjnsn600023b6j6f7ziw63%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyyjnsn600033b6jok6ug8ch%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyyjnsn600053b6jk83lgdmo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyyjnsn600023b6j6f7ziw63%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyyjnsn600013b6jiiw5bgeh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A13%257D%255D%257D%255D%252C%2522id%2522%253A%2522clyyjnsn600023b6j6f7ziw63%2522%252C%2522activeTabId%2522%253A%2522clyyjnsn600013b6jiiw5bgeh%2522%257D%252C%2522clyyjnsn600053b6jk83lgdmo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyyjnsn600043b6jrujgfzam%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyyjnsn600053b6jk83lgdmo%2522%252C%2522activeTabId%2522%253A%2522clyyjnsn600043b6jrujgfzam%2522%257D%252C%2522clyyjnsn600033b6jok6ug8ch%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clyyjnsn600033b6jok6ug8ch%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), after some clicking around on different options, the inputValue and value get out of sync (look at the console).

![image](https://github.com/user-attachments/assets/54e5785b-9449-43e3-8d7e-4386043f83e8)

I have no idea why the ark-ui docs work and this repro, park demo and my own components don't
they seem to be almost exactly the same

**Comment by segunadebayo** [comment] 2024-07-24 15:39
After some digging, I found that this was a regression in Zag.js and was fixed in the last two releases.

We need a new release @cschroeter to resolve this issue.

**Comment by segunadebayo** [comment] 2024-07-25 15:43
New version has been released.

If the issue persists after the release, I'll re-open it.

**Closed by segunadebayo** 2024-07-25 15:43 UTC
Labels: pkg: react, component: combobox
