### ISSUE TITLE
[Menu] Disabled trigger doesn't prevent menu from opening

### ISSUE THREAD

**Issue by aureldussauge** [chakra-ui/ark#1676] opened 2023-11-10 10:37 UTC
### Description

When I set the attribute `disabled` on a `Menu.Trigger` and click on it, I expect it to remain closed, but the menu opens instead

### Link to Reproduction

https://codesandbox.io/p/sandbox/nostalgic-water-kd8ncp?file=%2Fapp%2Fpage.tsx%3A5%2C11

### Steps to reproduce

1. Click on the disabled button

### Ark UI Version

1.0.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome 117

**Comment by cschroeter** [comment] 2023-11-10 10:50
@aureldussauge 

Thanks for taking your time to create this issue. This is a funny issue since I can not reproduce this outside of Codesandbox:

 

https://github.com/chakra-ui/ark/assets/1846056/ecdadd32-0736-429d-ae10-f5a162175cd5

**Comment by cschroeter** [comment] 2023-11-10 15:05
Fixed with https://github.com/chakra-ui/zag/commit/913c45435300cc41b6d434e71a4002adfcfe12a8

Will be available in the next release.

**Closed by cschroeter** 2023-11-10 15:05 UTC
Labels: bug
