### ISSUE TITLE
[Vue]: Toast / Environment not exported

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/ark#997] opened 2023-05-25 05:25 UTC
### Description

According to the changelog https://ark-ui.com/docs/vue/overview/changelog, the `Toast`, and `Environment` components were added, however they are not exported from `ark-ui/vue`

### Link to Reproduction

N/A

### Steps to reproduce

N/A

### Ark UI Version

0.3

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

**Comment by cschroeter** [comment] 2023-05-25 20:49
Thanks for taking your time to report this bug. The issue is fixed in `@ark-ui/vue` version `0.4.0`

**Closed by cschroeter** 2023-05-25 20:49 UTC
Labels: bug
