### ISSUE TITLE
asChild not working on Switch

### ISSUE THREAD

**Issue by hjoelh** [chakra-ui/ark#1833] opened 2023-12-05 17:27 UTC
### Description

asChild prop (on Switch) doesn't seem to be working with any other element than `label`

https://github.com/chakra-ui/ark/assets/68335961/5e015a40-2ab9-43fb-91d3-bc2c1cf5ec7a

### Link to Reproduction (or Detailed Explanation)

setup basic switch

### Steps to Reproduce

setup basic switch, add asChild to root, should stay working ✅

(with asChild)
below root add a label element, stays working ✅
below root add div, button etc, doesn't work ❌

### Ark UI Version

"^1.1.0"

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome

**Comment by segunadebayo** [comment] 2023-12-05 20:54
Hi @hjoelh,

This is by design. The Switch, Checkbox, and Radio's semantic structure is such that a `label` is required to toggle the underlying input element. Otherwise, the HTML and accessibility structure will be invalid.

We should probably mention this in the docs @Omikorin and maybe add a validation logic for this in Zag.js

**Closed by segunadebayo** 2023-12-05 20:54 UTC

**Comment by Omikorin** [comment] 2023-12-05 21:01
> Hi @hjoelh,
> 
> This is by design. The Switch, Checkbox, and Radio's semantic structure is such that a `label` is required to toggle the underlying input element. Otherwise, the HTML and accessibility structure will be invalid.
> 
> We should probably mention this in the docs @Omikorin and maybe add a validation logic for this in Zag.js

Yeah, I think so. For example, we may also add some explanation of this design to the introduction.
