### ISSUE TITLE
[Tags Input] - Can't commit changes

### ISSUE THREAD

**Issue by FilipePfluck** [chakra-ui/ark#2003] opened 2024-01-09 18:05 UTC
### Description

The changes made to a tag can't be commited, and once I enter editing mode I can't create new tags either. It's not working by mouse nor by keyboard. 
Expected behaviour: 
Pressing Enter or double-clicking on the tag will put it in edit mode, allowing the user change its value and press Enter to commit the changes.
What happens: 
Pressing enter or double-clicking on the tag will put it in edit mode, but the user can't commit the changes by pressing enter.

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/docs/components/tags-input

### Steps to Reproduce

open the link
select one tag
edit it 
press enter and see the changes are not commited

### Ark UI Version

1.0.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment] 2024-01-10 09:43
@FilipePfluck 

Thanks for taking your time to create this issue. I can confirm the issue. The reason is that when the `ItemInput` is rendered within the `Item` it breaks. So the following example works:

```tsx
<TagsInputItemProvider key={index} value={{ index, value }}>
  <TagsInput.Item key={index} index={index} value={value}>
      <TagsInput.ItemText>{value}</TagsInput.ItemText>
      <TagsInput.ItemDeleteTrigger>Delete</TagsInput.ItemDeleteTrigger>
  </TagsInput.Item>
  <TagsInput.ItemInput />
</TagsInputItemProvider>
```

**Comment by Omikorin** [comment] 2024-01-15 18:09
Need to check solid and vue just in case

**Comment by cschroeter** [comment] 2024-01-26 22:27
This issue will be fixed within the next major release.

**Closed by cschroeter** 2024-01-26 22:27 UTC
Labels: component: tags input, type: bug
