### ISSUE TITLE
Updating state with useSearchParams on Select component causes multiple reenders

### ISSUE THREAD

**Issue by juliomuhlbauer** [chakra-ui/ark#1817] opened 2023-12-03 19:37 UTC
### Description

When using Nexjjs's useSearchParams hook with Select component causes multiple reenders.

### Link to Reproduction (or Detailed Explanation)

https://use-search-param-ark.vercel.app/search-param

### Steps to Reproduce

1. Go to the reproduction
2. Open console
3. Change the select value

### Ark UI Version

1.1.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Additional Information

GitHub Repo: https://github.com/juliomuhlbauer/use-search-param-ark

Context:
I had opened an issue first on next-usequerystate https://github.com/47ng/next-usequerystate/issues/370, but it wasn't the problem.
Then I opened an issue in Ark: https://github.com/chakra-ui/ark/issues/1738 and Nextjs: https://github.com/vercel/next.js/issues/58684

We tested different solutions. And I think the problem is with Ark UI.

I also tested with Radix and it is working fine: https://use-search-param-ark.vercel.app/search-param-radix

https://github.com/chakra-ui/ark/assets/53458125/fb239146-1517-4d9d-939d-054b71cef7d9

**Comment by juliomuhlbauer** [comment] 2023-12-03 19:43
Seems like adding a key to the Select works.
But I don't think is a clever solution as it reenders the component every searchParam change and it would be a bad DX for devs using Nextjs.
https://github.com/chakra-ui/ark/assets/53458125/2f62c332-733b-4c15-85ca-3cf7ce1fead9

**Comment by cschroeter** [comment] 2023-12-05 08:39
@juliomuhlbauer

After reviewing the [issue](https://github.com/vercel/next.js/issues/58684), it appears there's also a concern related to [Radix](https://github.com/vercel/next.js/issues/58684#issuecomment-1837568438).

Currently, the solution from our end is unclear. If you identify the root cause and believe a fix can be implemented within Ark, please feel free to reopen this issue. We're closing it for now due to the lack of a clear resolution path.

**Closed by cschroeter** 2023-12-05 08:39 UTC
