### ISSUE TITLE
Bug: Keyboard navigation through Tabs moves entire component around.

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/ark#2545] opened 2024-06-10 12:14 UTC
### Description

When using arrow keys to navigate between different tabs, the entire component jumps. It seems to happen across all supported frameworks.

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/react/docs/components/tabs

### Steps to Reproduce

1. Go to https://ark-ui.com/react/docs/components/tabs
2. Focus tab list with keyboard.
3. Use arrows keys to move left and right (possibly quickly)
4. Watch the tab component jump.

### Ark UI Version

3.2.1

### Framework

- [X] React
- [X] Solid
- [X] Vue

### Browser

Firefox, Chrome, Safari

### Additional Information

The jumping seems to occur most frequently on Firefox, but can be reproduced on chrome/safari by spamming arrows and switching directions. I don't think this is a docs issue, as I've had the exact same issue in my own component library.

**Comment by segunadebayo** [comment] 2024-06-10 15:04
After digging into this, it seems to be caused by the presence machine.

Working on a fix for this.

**Comment by segunadebayo** [comment] 2024-06-11 11:19
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Closed by segunadebayo** 2024-06-11 11:19 UTC
